---

- hosts: vagrant
  become: yes
  vars:
    packages:
      - gcc 
      - make 
      - perl 
      - kernel-devel 
      - kernel-devel-4.18.0-348.el8.0.2.x86_64
      - elfutils-libelf-devel 
      - vagrant 
      - VirtualBox-6.1
  tasks:
    - name: "Update yum"
      yum:
        update_cache: yes
    - name: "Install yum-utils and epel-release"
      yum:
        name:
          - "yum-utils"
          - "epel-release"
        state: latest
    - name: "Add VirtualBox repo"
      get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
        dest: /etc/yum.repos.d/virtualbox.repo
    - name: "Add Hashicorp Repo"
      get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
    - name: "install packages"
      yum:
        name: "{{ packages }}"
        state: latest
    - name: "make /files directory"
      file:
        path: /files
        state: directory
    - name: "Download VirtualBox extensions"
      uri:
        method: GET
        url: https://download.virtualbox.org/virtualbox/6.1.32/Oracle_VM_VirtualBox_Extension_Pack-6.1.32-149290.vbox-extpack
        creates: /files/Oracle_VM_VirtualBox_Extension_Pack-6.1.32-149290.vbox-extpack
    - name: "Install VirtualBox extension pack"
      shell:
        cmd: "echo 'y' | VBoxManage extpack install /files/Oracle_VM_VirtualBox_Extension_Pack-6.1.32-149290.vbox-extpack"
    - name: "Reload VirtualBox"
      shell:
        cmd: "/sbin/vboxconfig"
