---

- hosts: vagrant
  become: yes
  tasks:
    - name: "Update yum"
      yum:
        update_cache: yes
    - name: "Install yum-utils and epel-release"
      yum:
        name:
          - "yum-utils"
          - "epel-release"
        state: latest
    - name: "Add repositories for installation"
      get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
        dest: /etx/yum.repos.d/virtualbox.repo
    - name: "Add Hashicorp Repo"
      get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo